version: '3.7'
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis-container
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - /src/redis.conf:/tmp/redis.conf

  api:
    build: .
    image: node-docker-redis-api:latest
    container_name: api
    restart: unless-stopped
    network_mode: bridge
    command: /bin/sh -c 'nodemon -e js,html server.js'
    ports:
      - "8080:9000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - .:/src
      - /src/node_modules
    # environment:
    #   NODE_ENV: dev
    #   REDIS_URL: redis://cache
    links:
      - redis

  sendmail:
    build: .
    image: node-docker-redis-sendmail:latest
    container_name: sendmail
    restart: unless-stopped
    network_mode: bridge
    command: /bin/sh -c 'nodemon -e js,html server-sendmail.js'
    ports:
      - "3001:3001"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

    volumes:
      - .:/src
      - /src/node_modules